In [1]:
# Step 1: NumPyをインポート
import numpy as np

# Step 2: AとBの行列を定義
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])

# AとBの行列を表示
print("行列 A:\n", A)
print("行列 B:\n", B)

# Step 3: 行列の積を計算
result = np.dot(A, B)

# Step 4: 計算結果を表示
print("行列の積:\n", result)

# Step 5: 行列の要素の最大値を求める
max_value = np.max(result)
print("行列の最大値:", max_value)


行列 A:
 [[0 1]
 [2 3]
 [4 5]]
行列 B:
 [[0 1 2 3]
 [4 5 6 7]]
行列の積:
 [[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
行列の最大値: 47
